"""init tables

Revision ID: ff41bfd03dc2
Revises: 
Create Date: 2026-01-01 11:03:17.729234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff41bfd03dc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mac_address', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_seen_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mac_address')
    )
    op.create_table('routers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('site_name', sa.Text(), nullable=False),
    sa.Column('wan_public_ip', postgresql.INET(), nullable=True),
    sa.Column('lan_ip', postgresql.INET(), nullable=True),
    sa.Column('radius_secret', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('router_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('rate_limit', sa.Text(), nullable=True),
    sa.Column('session_timeout', sa.Integer(), nullable=True),
    sa.Column('idle_timeout', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('router_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('amount_kes', sa.Integer(), nullable=False),
    sa.Column('merchant_request_id', sa.Text(), nullable=True),
    sa.Column('checkout_request_id', sa.Text(), nullable=True),
    sa.Column('mpesa_receipt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'CANCELLED', 'TIMEOUT', name='paymentstatus'), nullable=True),
    sa.Column('status_reason', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('raw_callback_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id'),
    sa.UniqueConstraint('mpesa_receipt')
    )
    op.create_table('radius_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('router_id', sa.UUID(), nullable=True),
    sa.Column('device_id', sa.UUID(), nullable=True),
    sa.Column('acct_session_id', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=True),
    sa.Column('framed_ip', postgresql.INET(), nullable=True),
    sa.Column('nas_ip_address', postgresql.INET(), nullable=True),
    sa.Column('start_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_update_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('stop_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('input_octets', sa.BigInteger(), nullable=True),
    sa.Column('output_octets', sa.BigInteger(), nullable=True),
    sa.Column('terminate_cause', sa.Text(), nullable=True),
    sa.Column('raw_packet_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['router_id'], ['routers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('radius_sessions')
    op.drop_table('payments')
    op.drop_table('access_grants')
    op.drop_table('routers')
    op.drop_table('devices')
    # ### end Alembic commands ###
